<?php

declare(strict_types=1);

namespace App\Lab\Command;

use App\Domain\RiskProfile;
use App\Engine\Php\PhpRiskEngine;
use App\Lab\FixtureCases;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

/**
 * Writes fixtures/risk-cases.json.
 *
 * The expected verdicts are produced by the PHP engine, which raises a fair objection: does that
 * not make PHP the reference implementation and the parity claim circular?
 *
 * No, because the fixture is checked from both ends:
 *
 *   1. `go/risk/fixtures_test.go` reads this file and asserts Go agrees with every value in it. If
 *      PHP were wrong, that test fails — it is not comparing Go to PHP at runtime, it is comparing
 *      Go to a committed artifact.
 *   2. The unit tests on both sides assert numbers derived *by hand* from docs/risk-model.md, so
 *      neither implementation is trusted as the source of truth for the values that matter most.
 *
 * The file is committed, so a change to it shows up as a reviewable diff. A silent shift in a
 * decision boundary is exactly the kind of change that should be impossible to merge unnoticed.
 */
#[AsCommand(
    name: 'lab:fixtures:generate',
    description: 'Regenerate fixtures/risk-cases.json from the case corpus',
)]
final class GenerateFixturesCommand extends Command
{
    public function __construct(
        private readonly PhpRiskEngine $engine,
        private readonly int $treeCount,
        private readonly string $fixturePath,
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $cases = [];

        foreach (FixtureCases::all() as $case) {
            $expected = [];

            foreach (RiskProfile::cases() as $profile) {
                $assessment = $this->engine->assess($case['input'], $profile);

                $expected[$profile->value] = [
                    'riskScore' => $assessment->score,
                    'status' => $assessment->status->value,
                    'decisionReason' => $assessment->reason->value,
                ];
            }

            $cases[] = [
                'id' => $case['id'],
                'description' => $case['description'],
                'input' => FixtureCases::toArray($case['input']),
                'expected' => $expected,
            ];
        }

        $document = [
            '_readme' => 'Generated by "make fixtures". Do not edit by hand. '
                .'Every engine must reproduce every expected verdict exactly; see docs/risk-model.md.',
            'specification' => 'docs/risk-model.md',
            // Recorded because the ENSEMBLE expectations are only valid for this forest size.
            // A fixture that did not state it would silently "fail" whenever the sweep changed it.
            'treeCount' => $this->treeCount,
            'caseCount' => \count($cases),
            'cases' => $cases,
        ];

        $json = json_encode(
            $document,
            \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES | \JSON_THROW_ON_ERROR,
        );

        if (false === file_put_contents($this->fixturePath, $json."\n")) {
            $io->error(\sprintf('Could not write %s', $this->fixturePath));

            return Command::FAILURE;
        }

        $io->success(\sprintf(
            'Wrote %d cases x %d profiles to %s (treeCount=%d)',
            \count($cases),
            \count(RiskProfile::cases()),
            $this->fixturePath,
            $this->treeCount,
        ));

        return Command::SUCCESS;
    }
}
