package risk

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The Go half of the parity guarantee.
//
// fixtures/risk-cases.json is generated by the PHP engine, which raises the obvious objection: if
// PHP produces the expectations and PHP is then checked against them, the whole thing is circular.
//
// This test is what breaks the circle. Go reads the committed artifact and has to agree with every
// value in it, without ever consulting the PHP implementation. Combined with the hand-derived
// expectations in engine_test.go — the same numbers asserted independently on both sides — that
// means a shared mistake would have to be made twice, in two languages, and still land on the
// values a human worked out from docs/risk-model.md.
//
// `make parity-test` additionally compares all three engines at runtime. That catches drift in the
// two adapters; this catches drift in the core.

type fixtureDocument struct {
	TreeCount int           `json:"treeCount"`
	CaseCount int           `json:"caseCount"`
	Cases     []fixtureCase `json:"cases"`
}

type fixtureCase struct {
	ID          string                    `json:"id"`
	Description string                    `json:"description"`
	Input       fixtureInput              `json:"input"`
	Expected    map[string]fixtureVerdict `json:"expected"`
}

type fixtureInput struct {
	AmountMinor      int64   `json:"amountMinor"`
	Currency         string  `json:"currency"`
	Country          string  `json:"country"`
	CardBIN          string  `json:"cardBin"`
	MerchantID       string  `json:"merchantId"`
	DeviceID         string  `json:"deviceId"`
	BINCountry       *string `json:"binCountry"`
	DeviceTxCount24h int64   `json:"deviceTxCount24h"`
	MerchantRiskTier int64   `json:"merchantRiskTier"`
}

type fixtureVerdict struct {
	RiskScore      int64  `json:"riskScore"`
	Status         string `json:"status"`
	DecisionReason string `json:"decisionReason"`
}

func (f fixtureInput) toInput() Input {
	in := Input{
		AmountMinor:      f.AmountMinor,
		Currency:         f.Currency,
		Country:          f.Country,
		CardBIN:          f.CardBIN,
		MerchantID:       f.MerchantID,
		DeviceID:         f.DeviceID,
		DeviceTxCount24h: f.DeviceTxCount24h,
		MerchantRiskTier: f.MerchantRiskTier,
	}

	// A null issuer country stays the empty string, which the core reads as "unknown".
	if f.BINCountry != nil {
		in.BINCountry = *f.BINCountry
	}

	return in
}

func loadFixtures(t *testing.T) fixtureDocument {
	t.Helper()

	path := filepath.Join("..", "..", "fixtures", "risk-cases.json")

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("cannot read %s: %v\nRun 'make fixtures' to generate it.", path, err)
	}

	var doc fixtureDocument
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("%s is not valid JSON: %v", path, err)
	}

	if len(doc.Cases) == 0 {
		t.Fatal("the fixture file contains no cases")
	}
	if len(doc.Cases) != doc.CaseCount {
		t.Fatalf("fixture declares %d cases but contains %d", doc.CaseCount, len(doc.Cases))
	}

	return doc
}

func TestGoAgreesWithEveryFixture(t *testing.T) {
	doc := loadFixtures(t)

	// The ENSEMBLE expectations are only meaningful for the forest size they were generated
	// with, so the fixture records it and this test honours it. Without this, a sweep that
	// changed the default would make every ensemble case "fail" for no real reason.
	original := TreeCount
	t.Cleanup(func() { TreeCount = original })
	TreeCount = doc.TreeCount

	for _, tc := range doc.Cases {
		t.Run(tc.ID, func(t *testing.T) {
			input := tc.Input.toInput()

			for profileName, want := range tc.Expected {
				got := Assess(input, Profile(profileName))

				if got.Score != want.RiskScore ||
					string(got.Status) != want.Status ||
					got.Reason != want.DecisionReason {
					t.Errorf(
						"%s / %s (%s)\n  go:       %d / %s / %s\n  fixture:  %d / %s / %s",
						tc.ID, profileName, tc.Description,
						got.Score, got.Status, got.Reason,
						want.RiskScore, want.Status, want.DecisionReason,
					)
				}
			}
		})
	}
}

// TestFixturesCoverEveryReasonCode makes the corpus's own coverage a tested property.
//
// A fixture suite that never produces a given reason cannot detect a regression in it. This is the
// test that caught the original design defect: five reason codes were declared in the contract and
// structurally impossible to emit, and no amount of adding cases would have surfaced them.
func TestFixturesCoverEveryReasonCode(t *testing.T) {
	doc := loadFixtures(t)

	observed := map[string]bool{}
	for _, tc := range doc.Cases {
		for _, verdict := range tc.Expected {
			observed[verdict.DecisionReason] = true
		}
	}

	for _, reason := range AllReasonCodes() {
		if !observed[reason] {
			t.Errorf("no fixture produces reason %q, so nothing would detect a regression in it",
				reason)
		}
	}
}

func TestFixturesCoverEveryStatus(t *testing.T) {
	doc := loadFixtures(t)

	observed := map[string]bool{}
	for _, tc := range doc.Cases {
		for _, verdict := range tc.Expected {
			observed[verdict.Status] = true
		}
	}

	for _, status := range []Status{StatusApproved, StatusChallenged, StatusDeclined} {
		if !observed[string(status)] {
			t.Errorf("no fixture produces status %q", status)
		}
	}
}
